reader:
    type: ES
    url: 'http://127.0.0.1:9200'
    scroll_size: 10000
    timeout: 90s
models:
    -   name: NVISO - Beaconing
        sql_query: >
            SELECT BroFilter.id_orig_h as origin,
                   BroFilter.server_name as destination,
                   CAST(timestamp AS FLOAT) AS time,
                   0 AS elapsed_time
            FROM nviso_brofilter
            ORDER BY BroFilter.id_orig_h, BroFilter.server_name, timestamp
        bucket: [origin, destination]
        metrics: [str, str, int, 'python_eval(abs(row[2] - prev_row[2]) if prev_row else None)']
        targets: [elapsed_time]
        batch_size: 10000
        detection:
            method: isolation_forest
            # Trigger on high density
            trigger_on: high
            sensitivity: 60
        outlier_message:
            title: This connection sends data with a current interval
            content: 'Process name: {origin} - Child: {destination} - Elapsed time: {elapsed_time}'
        plotting:
            enable: True
            output: plots
